---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: dev
spec:
  releaseName: nginx
  chart:
    git: git@github.com:ranvijay12/fluxcd-helm-operator.git
    path: webservice
    ref: master
  rollback:
     enable: true
     wait: false
  values:
    fullnameOverride: nginx
    nameOverride: nginx
    image:
      repository: nginx
      tag: latest
    service:
      type: ClusterIP
      data:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http    
    replicaCount: 1
    hpa:
      enabled: false
    liveness:
      port: 80
      path: /
    readiness:
      port: 80
      path: /
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    annotations:
      prometheus.io/path: "/nginx/prometheus"
      prometheus.io/port: "80"
      prometheus.io/scrape: "true"
    vs:
      enable: true
      #host name/dns name 
      host: "*"
      #gateway used by this svc to communicate from outside of cluster
      gateway: dev-gateway
      #prefix is the path attached to the host
      prefix: nginx
      destination:
        port: 80    
