---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:ranvijay12/fluxcd-helm-operator.git
    path: webservice
    ref: master
  rollback:
    enable: true
    wait: false
  values:
    initContainers:
      enable: true
      data: 
      - name: init
        image: alpine:3.10
        command:
        - sleep
        - "1"
    nameOverride: podinfo
    fullnameOverride: podinfo
    annotations:
        prometheus.io/port: "9797"
        prometheus.io/scrape: "true"
    env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
    image:
      repository: stefanprodan/podinfo
      tag: 3.1.5
    replicaCount: 1
    command:
        enable: true   
        data:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
        - --ui-message='Welcome to Flux'
    liveness:
      enabled: true
      port:  9898
      path: /healthz
    readiness:
      enabled: true
      port: 9898
      path: /readyz
    hpa:
      enabled: false
    service:
      type: ClusterIP
      data:
      - port: 9898
        targetPort: 9898
        protocol: TCP
        name: http
    vs:
      enable: true
      #host name/dns name 
      host: "*"
      #gateway used by this svc to communicate from outside of cluster
      gateway: dev-gateway
      #prefix is the path attached to the host
      prefix: podinfo
      destination:
        port: 9898
    ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
    resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi       
