---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:ranvijay12/fluxcd-helm-operator.git
    path: webservice
    ref: master
  rollback:
    enable: true
  values:
    annotations:
        prometheus.io/port: "9797"
        prometheus.io/scrape: "true"
    image:
      repository: stefanprodan/podinfo
      tag: dev-hdtwcel9
    replicaCount: 1
    liveness:
      enabled: true
      port:  9797
      path: /health
    readiness:
      enabled: true
      port: 9797
      path: /ready 
    hpa:
      enabled: false
