---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:ranvijay12/fluxcd-helm-operator.git
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: podinfo
      tag: stefanprodan/podinfo:3.2.4
    replicaCount: 1
    hpa:
      enabled: false
