apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webservice.fullname" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4}}      
spec:
{{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "webservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "webservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers.enable }}
      initContainers:
         {{- toYaml .Values.initContainers.data | nindent 7}}     
      {{- end }}  
      containers:
        - name: {{ .Values.nameOverride }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.ports}}
          - name: {{ .name }}
            containerPort: {{ .containerPort }}
            protocol: {{ .protocol }}
          {{- end }}
          {{- if .Values.commands.enabled }}
          commands:
          {{- toYaml .Values.enabled.values | nindent 12}}
          {{- end}}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            {{- range $.Values.configmapDeployment }}
            - name: configmap
              valueFrom:
                configMapRef:
                  name: {{ .Values.configmapDeployment.key }}
                  key:  {{ .Values.configmapDeployment.value }}        
            {{- end}}
            - name: POD_NAME
              valueFrom:
               fieldRef:
                fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
               fieldRef:
                fieldPath: metadata.namespace
         {{- if .Values.liveness.enabled }}       
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.liveness.port }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
         {{- end }}     
         {{- if .Values.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: {{ .Values.readiness.port }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
         {{- end }}     
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

