apiVersion: v1
kind: Service
metadata:
  name: {{ include "webservice.fullname" . }}
  labels:
    {{- include "webservice.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4}}      
spec:
  type: {{ .Values.service.type }}
  {{- range $.Values.service.data}}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort}}
      protocol: {{ .protocol}}
      name: {{ .name}}
  {{- end}}    
  selector:
    {{- include "webservice.selectorLabels" . | nindent 4 }}
